### ISSUE TITLE
Unable to start Unicorn Binance Websocket Api CRITICAL:root:BinanceWebSocketApiManager._create_stream_thread()

### ISSUE THREAD

**Issue by bashman** [oliver-zehentleitner/unicorn-binance-websocket-api#145] opened 2021-02-03 22:00 UTC
Greetings. 

I'm getting this error:

`
CRITICAL:root:BinanceWebSocketApiManager._create_stream_thread() stream_id=d22cb27d-04f1-41c2-a100-4ecab6062091 error: 7 - can't register atexit after shutdown
`

Possible  reason:
Python 3.9

I am running Unicorn Binance Websocket Api in other computer and this runs very well, and fast  but python versión is python 3.8

**Comment by oliver-zehentleitner** [comment] 2021-02-04 20:56
Just to link the python3.9 issues: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/131

**Comment by oliver-zehentleitner** [comment] 2021-02-13 17:22
Hi Bashman, could you provide more infos, just to get a picture of this problem?
How often does this happen? What happens then? Is the lib down or do the streams reconnect?

**Comment by bashman** [comment] 2021-02-14 06:46
> Hi Bashman, could you provide more infos, just to get a picture of this problem?
> How often does this happen? What happens then? Is the lib down or do the streams reconnect?

Hi. Oliver, no, is only this message. UBWSA, don't works before...

**Comment by xilopaint** [comment] 2021-02-14 07:41
Using Python 3.9 the issue can be reproduced just like this:

```python3
from unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager import BinanceWebSocketApiManager

API_KEY = '*'
API_SECRET = '*'


binance_websocket_api_manager = BinanceWebSocketApiManager(
    exchange='binance.com-futures',
)

binance_websocket_api_manager.create_stream(
    channels=['!userData'],
    markets=['arr'],
    api_key=API_KEY,
    api_secret=API_SECRET
)
```

```
$ ./sample.py
CRITICAL:root:BinanceWebSocketApiManager._create_stream_thread() stream_id=623d563a-88fb-4304-9ffe-94549e463825  - RuntimeError error_msg:  - cannot schedule new futures after interpreter shutdown - stopping and shutting down - read https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/131 for further information!
```

**Comment by oliver-zehentleitner** [comment] 2021-02-14 09:10
This is a different error as mentioned in the first post, but it seems to be related to python3.9:
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/131

**Comment by xilopaint** [comment] 2021-02-14 09:16
> This is a different error as mentioned in the first post, but it seems to be related to python3.9:
> #131

Oh, I didn't realize it was a different error. Any idea about the fix or it's a bug in Python 3.9?

**Comment by oliver-zehentleitner** [comment] 2021-02-23 14:17
All I know is: "cannot schedule new futures after interpreter shutdown"

If someone finds a reason why the interpreter is down, we can try to fix that. But this error is to generic. And it only happens with 3.9 so far.

I will close this. Anyone can reopen with new infos!

**Closed by oliver-zehentleitner** 2021-02-23 14:17 UTC
Labels: bug, python3.9

**Comment by TBMoonwalker** [comment] 2022-03-13 07:22
The python-telegram-bot had the same problem with Python 3.9 - maybe you can find the fix there.

- https://stackoverflow.com/questions/70673175/runtimeerror-cannot-schedule-new-futures-after-interpreter-shutdown
- https://github.com/python-telegram-bot/python-telegram-bot/issues/2863

**Comment by oliver-zehentleitner** [comment] 2022-03-13 09:16
thanks, buts its solved :)

**Comment by oliver-zehentleitner** [comment] 2022-03-13 09:17
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/issues/131

**Comment by TBMoonwalker** [comment] 2022-03-13 09:23
No, it isn't. Tested it with latest Python 3.9 docker image on a Raspberry PI 4 (4GB) in a Kubernetes environment. Exactly the same image with the latest Python version 3.8 is running fine. If it works for you now - maybe there is a timing problem on "slower" machines?

**Comment by oliver-zehentleitner** [comment] 2022-03-13 09:35
Which UBWA Version do you use? I am sure the issue is fixed on reproducable systems.

I fixed it last week.... so you must use the latest version and `high_performance` must not be True!

If still persists, please open a new issue with logfiles and the error msg. Is it realy thrown from the same code as before?

I need a way to reproduce the error.

**Comment by oliver-zehentleitner** [comment] 2022-03-13 09:38
It definitly was a timing problem. Since my update the code blocks till thread AND coroutine loop of the new stream are ready started which avoids the error in our tests.
